name: Deploy website to Heroku
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v2
      - name: linter
        uses: michaelw90/PHP-Lint@master
      - name: security check
        uses: symfonycorp/security-checker-action@v2
      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        with:
          args: analyse src/ --level=5
      - uses: akhileshns/heroku-deploy@v3.5.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_NAME}} #Must be unique in Heroku
          heroku_email: "yannis.b8@gmail.com"